spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/crm
    username: postgres
    password: gmb1998
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
springdoc:
  swagger-ui:
    disable-swagger-default-url: true
    path: /example/market_jpa